config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'cocktails#home'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def home
  end

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail_id)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_new.html.erb
<%= simple_form_for (Cocktail.new) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/cocktails/home.html.erb
<div class="container d-flex flex-column justify-content-between">
  <div class="headings">
    <h1>Mister</h1>
    <h2 class="heading_home">Cocktail</h2>
  </div>

  <div class="img_preview">
    <%= cl_image_tag("cocktail_home", :class => "img_preview") %>
  </div>

  <div class="enter_link">
    <%= link_to cocktails_path do %>
      <button class="btn_transparent">E N T E R</button>
    <% end %>
  </div>



</div>

app/views/cocktails/index.html.erb
<div class="container">
  <div class="new_cocktail">
    <button type="button" class="btn_white" data-toggle="modal" data-target="#exampleModalCenter">
        Add cocktail
      </button>
  </div>

  <div class="headings">
    <h1>Mister</h1>
    <h2>Cocktail</h2>
  </div>



  <div class="cards">
    <% @cocktails.each do |cocktail| %>
      <% if cocktail.photo.present? %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= cl_image_path(cocktail.photo.key) %>)">
          <div class="cocktail_link">
            <%= link_to cocktail_path(cocktail) do %>
              <button class="btn_white_md"><%= cocktail.name %></button>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= cl_image_tag("cocktail_home", :class => "img_preview") %>)">
          <div class="cocktail_link">
            <%= link_to cocktail_path(cocktail) do %>
              <button class="btn_white_md"><%= cocktail.name %></button>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Add a new cocktail</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'cocktails/new' %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container d-flex flex-column justify-content-between">
  <div class="nav d-flex justify-content-between">
    <div class="back_link">
      <%= link_to cocktails_path do %>
        <button class="btn_white">Back</button>
      <% end %>
    </div>

    <div class="add_link">
      <button type="button" class="btn_white" data-toggle="modal" data-target="#exampleModalCenter">
        Add ingredient
      </button>
    </div>
  </div>

  <div class="headings_show">
    <h1>Mister</h1>
    <h2><%= @cocktail.name %></h2>
  </div>

  <div class="main_image">
    <% if @cocktail.photo.present? %>
      <%= cl_image_tag @cocktail.photo.key, height: 267, width: 400, crop: :fill %>
    <% else %>
      <%= cl_image_tag("cocktail_home", :class => "img_preview") %>
    <% end %>
  </div>

  <div class="list_ingredients">
    <ul>
      <% @cocktail.doses.each do |dose| %>
        <li>
          <%= dose.description %> <%= dose.ingredient.name %> <%= link_to dose_path(dose), method: :delete, data: {confirm: "Are you sure?"}  do%>
          <i class="far fa-trash-alt"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Add ingredients to your <%= @cocktail.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'doses/new' %>
      </div>
    </div>
  </div>
</div>

app/views/doses/_new.html.erb
<h1>Add ingredients to your <%= @cocktail.name %></h1>

<%= simple_form_for ([@cocktail, Dose.new]) do |f| %>
  <%= f.association :ingredient %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/doses/new.html.erb
<h1>Add ingredients to your <%= @cocktail.name %></h1>

<%= simple_form_for ([@cocktail, @dose]) do |f| %>
  <%= f.association :ingredient %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <style> @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@600&family=Roboto&family=Taviraj:wght@500&display=swap');</style>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>